In [1]:
import torch
import torch_geometric
from torch_geometric.data import Data, HeteroData
from torch_geometric.nn.models import GAT

#from model.extras.gat import GAT, GraphAttn



In [15]:
adjacency_matrix = torch.load('./data/scene_graphs/0.pt')[0]

edge_index = adjacency_matrix.nonzero(as_tuple=False).t().long()
print(edge_index)


#sg = Data(traj_sgs_tensor)
#sg

tensor([[  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   6,   6,
           6,   6,   6,   6,  13,  13,  13,  13,  13,  13,  13,  13,  13,  18,
          18,  18,  18,  18,  18,  18,  18,  18,  18,  21,  21,  21,  21,  21,
          21,  21,  21,  21,  21,  22,  22,  22,  22,  22,  22,  22,  22,  22,
          31,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,  32,  42,
          42,  42,  42,  42,  42,  42,  42,  42,  43,  43,  43,  43,  43,  43,
          43,  43,  43,  43,  50,  50,  50,  53,  53,  53,  53,  53,  53,  53,
          60,  60,  60,  60,  60,  60,  60,  60,  60,  60,  60,  60,  60,  60,
          60,  60,  60,  60,  60,  61,  61,  61,  61,  61,  61,  61,  61,  61,
          61,  76,  76,  76,  76,  76,  76,  76,  76,  76,  76,  77,  77,  77,
          77,  77,  77,  77,  80,  80,  80,  80,  80,  80,  80,  80,  80,  81,
          81,  81,  81,  81,  81,  81,  81,  81,  81,  84,  84,  84,  84,  84,
          84,  84,  84,  84,  84,  84,  84,  84,  84

In [24]:
import torch
from torch_geometric.data import Data
from torch_geometric.utils import dense_to_sparse, remove_isolated_nodes, mask_select

# Step 1: Create an adjacency matrix (example)
test = torch.tensor([[0, 2, 1],
                                  [5, 0, 0],
                                  [8, 0, 0]], dtype=torch.float)

#adjacency_matrix = torch.load('./data/scene_graphs/19.pt')[20]
adjacency_matrix = torch.load('./data/scene_graphs/19.pt')[0]

# Step 2: Convert the adjacency matrix to edge_index
# Get the indices where the adjacency matrix is non-zero
#edge_index = adjacency_matrix.nonzero(as_tuple=False).t().long()
#edge_attr = [adjacency_matrix[edge_index[0][i]][edge_index[1][i]] for i in range(len(edge_index[0]))]
edge_index, edge_attr = dense_to_sparse(adjacency_matrix)

# Step 3: Create node features (example: using a feature size of 1)
num_nodes = adjacency_matrix.size(0)
node_features = torch.randn(num_nodes, 1)  # Random features for each node

edge_index, edge_attr, mask = remove_isolated_nodes(edge_index, edge_attr)
node_features = mask_select(node_features, 0, mask)

# Step 4: Create the PyG Data object
data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_attr)
print(num_nodes)
print(edge_index)
print(len(edge_attr))

152
tensor([[ 30,  30,  30,  30,  30,  30,  30,  30,  30,  34,  34,  34,  34,  34,
          35,  35,  35,  35,  35,  35,  35,  54,  54,  54,  54,  54,  54,  54,
          54,  54,  54,  54,  60,  60,  60,  60,  60,  60,  60,  60,  60,  60,
          60,  60,  60,  60,  60,  64,  64,  64,  64,  64,  64,  64,  66,  66,
          66,  66,  66,  66,  66,  66,  66,  66,  66,  66,  66,  71,  71,  71,
          71,  71,  71,  71,  71,  71,  71,  82,  82,  82,  82,  82,  88,  88,
          88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  91,  91,  91,
          91,  91,  91,  91, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
         101, 102, 102, 102, 102, 107, 107, 107, 107, 107, 107, 116, 116, 116,
         116, 116, 116, 116, 116, 134, 134, 134, 134, 134, 134, 134, 142, 142,
         142, 142, 142, 142, 142],
        [ 54,  60,  66,  88,  91, 101, 116, 134, 142,  54,  60,  71, 101, 126,
          54,  60,  66,  71,  88, 101, 116,  30,  35,  60,  64,  66,  71,  82,
          88,

In [11]:
import torch
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(5, 5)*1
b = torch.ones(3, 5)*2
c = torch.ones(2, 5)*3
padded = pad_sequence([a, b, c],batch_first=True)
print(padded.size())
print(padded)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [2]:
non_geometric_polygon_layers = ['drivable_area', 'road_segment', 'road_block', 'lane', 'ped_crossing',
                                             'walkway', 'stop_line', 'carpark_area']
non_geometric_line_layers = ['road_divider', 'lane_divider', 'traffic_light']
non_geometric_layers = non_geometric_polygon_layers+non_geometric_line_layers
len(non_geometric_layers)

11

In [4]:

categories = [['animal', 'human', 'movable_object', 'static_object', 'vehicle'], 
              ['pedestrian', 'barrier', 'debris', 'pushable_pullable', 'trafficcone', 'bicycle_rack', 'bicycle', 'bus', 'car', 'construction', 'emergency', 'motorcycle', 'trailer', 'truck'],
              ['adult', 'child', 'construction_worker', 'personal_mobility', 'police_officer', 'stroller', 'wheelchair', 'bendy', 'rigid', 'ambulance', 'police']]

length = sum(len(c) for c in categories)
length

30

In [26]:
import shapely
from shapely.geometry import Polygon, MultiPolygon

single = Polygon([[0,5], [1,0], [5,5]])
single2 = Polygon([[8,5], [1,0], [5,5]])
print(single.area)
print(list(single.centroid.coords))

multi = MultiPolygon([single, single2])
print(multi.area)
print(list(multi.centroid.coords))
print(multi.centroid.x)


12.5
[(2.0, 3.333333333333333)]
20.0
[(3.0, 3.3333333333333335)]
3.0


In [16]:
import torch
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(5, 30)
b = torch.ones(2, 30)
c = torch.ones(1, 30)
d = pad_sequence([a, b, c])
print(d.size())
print(d)


torch.Size([5, 3, 30])
tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [5]:
import os
import numpy as np
a = np.zeros(2500)
l = []
for i in range(2454):
    data_path = '/data/Datasets/nuscenes_custom/data/actions/'
    path = data_path + str(i) + '.pt'
    if not os.path.exists(path):
        a[i] = 1
        l.append(i)

print(len(l))
print(l)
a[950:1100]


1
[2453]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
step = 3
intervals = []
for i in range(0, len(l), step):
    intervals.append([l[i], l[min(i+step, len(l)-1)]])
print(intervals)
print(len(intervals))


[[2453, 2453]]
1


In [21]:
import torch
import torch.functional as F
a = torch.zeros([5,5])
a[1,0] = 1
a

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [24]:
torch.argmax(a.T[0])

1

In [ ]:
from dataset_utils import *
def encode_edges(self, edge_attr):
        encodings = []
        for e in edge_attr:
            one_hot = torch.eye(len(edge_labels))[e]
            encodings.append(one_hot)
        return torch.stack(encodings)

encode_edges []

In [1]:
import torch
from torch_geometric.data import Data

# Assume data_list is your list of PyG Data objects
data_list = [Data(), Data()]  # Example list of Data objects

# Save the list of Data objects
torch.save(data_list, 'data_list.pt')

# Load the list of Data objects
loaded_data_list = torch.load('data_list.pt')


In [5]:
type(loaded_data_list[0])
hgfhsdjlgdf

NameError: name 'hgfhsdjlgdf' is not defined

In [12]:
import os
l = []
for i in range(2450):
    if not os.path.exists('/data/Datasets/nuscenes_custom/data/scene_graphs_pyg/'+str(i)+'.pt'):
        l.append(i)
print(len(l))
print(l)

1
[2399]


: 